### ISSUE TITLE
Make a single airdrop functions that *always* expects a minimum balance.

### ISSUE THREAD

**Issue by mikemaccana** [solana-developers/helpers#13]
Nick and I were talking and we both like this:

> We want to avoid people bothering the faucet unnecessarily but still make sure they can get devnet SOL when needed.
> We could make requestAndConfirmAirdropIfRequired()  the default technique.
> Eg, requestAndConfirmAirdrop() is the only function that gets airdrops,  always expects a balance in the function signature. So people, without thinking about it, never actually sends a request for devnet SOL when they don't need any.
> Will be a breaking change so will bump to version 2 when I do.

**Comment by nickfrosty** [comment]
This is now added :)
