### ISSUE TITLE
Speed up CI by caching the Solana CLI

### ISSUE THREAD

**Issue by mikemaccana** [solana-developers/helpers#3]
See https://github.com/solana-developers/node-helpers/pull/1#discussion_r1320010402

**Comment by nickfrosty** [comment]
we could also use the latest docker image that anza puts out. This will at least speed things up some:
https://hub.docker.com/r/solanalabs/solana

**Comment by mikemaccana** [comment]
Used https://github.com/metaDAOproject/setup-solana rather than [copying the web3.js CI and scripts](https://github.com/solana-labs/solana-web3.js/blob/94b4d494590b2ffbf60751bb74ed267b7228f012/.github/workflows/cicd.yml#L35-L50) - `setup-solana` is an indepent project and maintained as a GitHub action, so seems a little cleaner, and we're already using `setup-anchor` or `setup-solana` for `professional-education` and `program-examples` and Unboxed Movie Review program. 

5 seconds. 💨

![Screenshot 2024-05-08 at 10 54 07](https://github.com/solana-developers/helpers/assets/172594/19227aca-3a42-4cac-b78c-01c11dab6229)
