### ISSUE TITLE
ts: Module '"@solana-developers/helpers"' has no exported member 'createAccountsMintsAndTokenAccounts'

### ISSUE THREAD

**Issue by heyAyushh** [solana-developers/helpers#40]
```import { createAccountsMintsAndTokenAccounts } from '@solana-developers/helpers';```
createAccountsMintsAndTokenAccounts is not found. 

```
  "dependencies": {
    "@solana-developers/helpers": "^2.3.0",
  },
```

**Comment by mikemaccana** [comment]
Dupe of #42 (this is older but the other one has more comments).
