### ISSUE TITLE
Is there type declation file?

### ISSUE THREAD

**Issue by Lu-Derik** [solana-developers/helpers#49]
How to solve the problem in typescript? 
![image](https://github.com/user-attachments/assets/6e85a56d-96c1-4ca2-8768-c1822217b2e3)

**Comment by Lu-Derik** [comment]
I added a index.d.ts as the reminding, but cannot figure out this problem:

Could not find a declaration file for module '@solana-developers/helpers'. '/home/ldru/solana/solana-lab-non-transferable-token/node_modules/@solana-developers/helpers/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/solana-developers__helpers` if it exists or add a new declaration (.d.ts) file containing `declare module '@solana-developers/helpers';`ts(7016)

**Comment by dhl** [comment]
The project doesn't generate the type definitions at the moment, which is what https://github.com/solana-developers/helpers/pull/43 is trying to address.

Thanks for voicing out this project.

I was also inconvenienced by this problem.

**Comment by mikemaccana** [comment]
Sorry! `tsup` started giving us troubles and moving to `tsc` had some hiccups. **Fixed in 2.5.4.** Please raise a new issue if there are any more problems.
